server:
  port: 8082

name : zhangning

person:
  name: wangwu
  age : 18
  sex : 1


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: zhangning1994

  redis:
    host: 192.168.96.129
    port: 6379
mybatis:
  type-aliases-package: com.xcy.pojo
  mapper-locations: classpath:mapper/*.xml



